language: node_js
node_js:
- 10.0.0
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: o9aUtfNK7NwVgEyCN7lLMdeBgYr//yGwebfqeqU8928BjENtm3cA2I6ucChuIug05tcJYkMfDvTAWeDgWZrloUghI/zlfDFWZL3g9Lh0iu06UHBGeqcpckOxa15zzRTpHbZ4cn0oP/SFbFzS5aelB6Uh+2KHi7FhQy8rVVnCeMSU44dudDdosJRou3hR2q9S1tU7DFIQcYdqo65hKNLBOFUvlqD7th+HAifuE/rV1vHrJHIvPzPG7KyC2X0Y2fiKo0Zf79g29MV6QPJKCCxAp5B6Hg/d+5akMITKHW6K0vWJP+nZTFt3aqgpSoC51w/hY7QwlcB0JkOzcIy7fSKlRaoKiqq3sb7B5bLSA2IqUJ1csvhAnV+t6bCQW2yDV2nC9sIyICKTIQALX/kd49yXuE7gyVasp4mkixy/eC+a7i23f2Mr3uLH9THRosyeawNLz0RmNuGZF+six6n1kIXg/r1prgYfta1jRvF5pf09Vu7bEkORXQhDJyEe3BRb2UcMiqllOZJoiNTrv21aeGwZpkGn/1yvPY+FAZT3+cTyDKZvroTTH8Wk7Mcos0Pa/sOEdt9zjVx1PFaJNi+u69eZhQmTjhla5hXBVcpHaYvr7z+a5jBKHWtfJBvHYpaTEFgNiWNySsRmU6XJUoopti708FWz5QNr9D1haqsNlHVzpv4=
  app: tv-web-series-tracker
  on:
    repo: VOffoma/tv-series-tracker
    branch: develop
