language: node_js
node_js:
- 10.0.0
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: H0jkUKVvyfetrLuWuGmv9eIlYg2TbjJQwddhzOp963k34Vij29x27EQ4xrKLt3LCgY8Mfumu2w5vCaKIerfPtjPM1OMnvCwabljZpPd9nRHduKfYsD8r02qaC38JWLVEhPalRV4gGvNnHzP5cAStbMYHgQoBntodUiLS32xJahYcVKJcaN3igaLwmKKQqAtzu7DrY3oXjvGjP4OoC0G8ds6j+co/or2w8JjjHHXbpuIp6aPEM+4YKu3ZV8FUMrVY5Eh02CLASOmukTEJGR/+Njq08db8UJ5UPTu4ZmJGkYUp2Ak3KeCk26rf87tPagxipX3JnvtY45Tw2eJIZ/9bFlL02JPlIUI9pzPMVIf96/6JX5YKYKnS1fDG+6cScUZODhp1C1NAfqNzeuOQWsNVYZEoFWAplk0f1xz3l1EnoNpTWjj+xbaSp+Uyb1BZUzc71o+hUNTaDFWlqXluZHBLK/escw/T7Y1HtPLxNJWXU+tg5/g80Rrojo6FLg9LvtoVGP1EaGju444Y2gbP+n3DtbGBSXK2bzJC/0uYvjqQDwGSBTTn44cu5kcnbChWxSfKn0wh6KRMZd1oCuowMi/PnYQ462Y8DonAQs2rMzwGkaD5ilP74fqPjKE44ziWlh81vhwvyCZJYPX4mamtBACgmu/83UrNTDH/iAaEFIaA9iI=
  app: tv-web-series-tracker
  on:
    repo: VOffoma/tv-series-tracker
    branch: develop
