import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

dotenv.config();

const sender = 'test@test.com';

const transporter = nodemailer.createTransport({
  host: process.env.MAILHOST,
  port: process.env.MAILPORT,
  auth: {
    user: process.env.MAILUSER, // generated by Mailtrap
    pass: process.env.MAILPASSWORD, // generated by Mailtrap
  },
});

async function sendEmail(recipient, title, message) {
  const mailOptions = {
    from: sender,
    to: recipient,
    subject: title,
    text: message,
  };

  await transporter.sendMail(mailOptions);
}


export default { sendEmail };
